version: "3"
services:
    core:
        image: maciresearch/core_worker
        build: ./core_worker
        tty: true
        privileged: true
        ports:
            - "8080-8099:8080"
            - "5900-5909:5900"
        depends_on:
            - maci-backend
        restart: always
        hostname: core

