version: "3"
services:
    core:
        image: maciresearch/core_worker
        build: ./core_worker
        tty: true
        privileged: true
        cap_add:
            - NET_ADMIN
        ports:
            - "4038:4038"
        volumes:
             - /lib/modules:/lib/modules
        depends_on:
            - maci-backend
        restart: always
        hostname: core

