version: "3"
services:
  jupyter:
    image: jupyter/scipy-notebook
    command: ["start-notebook.sh", "--NotebookApp.token='' --allow-root"]
    deploy:
      replicas: 1
    ports: 
      - 8889:8888
    volumes:
      - jupyter-files:/home/jovyan
    depends_on: 
      - maci-backend
  maci-backend:
    build: ./maci-backend
    volumes:
      - simulation-framework:/maci/maci_backend/AppData/SimulationFramework
      - simulation-files:/maci/maci_backend/AppData/Simulations
      - jupyter-files:/maci/maci_backend/AppData/JupyterNotebook
      - worker-files:/maci/maci_backend/AppData/WorkerScript
      - ./maci_data:/maci_data
    ports: 
      - 63658:63658
  mininet:
    build:
      context: ./mininet_worker
    tty: true
    privileged: true
    tty: true
    environment:
     - DISPLAY
    volumes:
      - /lib/modules:/lib/modules
      - worker-files:/worker
    depends_on: 
      - maci-backend
    restart: always
    hostname: mininet


volumes:
  simulation-framework:
  simulation-files:
  jupyter-files:
  worker-files:
