version: "3"
services:
    jupyter:
        image: jupyter/scipy-notebook
        command: ["start-notebook.sh", "--NotebookApp.token='' --allow-root"]
        ports:
            - "8889:8888"
        volumes:
            - jupyter-files:/home/jovyan
        depends_on:
            - maci-backend
    maci-backend:
        image: maciresearch/maci-backend
        build: ./maci-backend
        volumes:
            - simulation-framework:/maci/maci_backend/AppData/SimulationFramework
            - simulation-files:/maci/maci_backend/AppData/Simulations
            - jupyter-files:/maci/maci_backend/AppData/JupyterNotebook
            - ./maci_data:/maci_data
        ports:
            - "63658:63658"

volumes:
    simulation-framework:
    simulation-files:
    jupyter-files:
