version: "3"
services:
    mininet-wifi:
        image: maciresearch/core_worker
        build: ./mininet-wifi_worker
		tty: true
        privileged: true
        environment:
			- DISPLAY
        volumes:
            - /sys:/sys
        depends_on:
            - maci-backend
        restart: always
        hostname: mininet-wifi
        cap_add:
            - ALL
        network_mode: "host"