version: "3"
services:
    mininet:
        build:
            context: ./mininet_worker
        tty: true
        privileged: true
        environment:
             - DISPLAY
        volumes:
             - /lib/modules:/lib/modules
        depends_on: 
             - maci-backend
        restart: always
        hostname: mininet
