version: "3"
services:
    mininet-wifi:
        build:
            context: ./mininet-wifi_worker
        privileged: true
        cap_add:
            - ALL
        network_mode: "host"
        tty: true
        environment:
            - DISPLAY
        depends_on:
            - maci-backend
        volumes:
            - /sys:/sys
        restart: always
        hostname: mininet-wifi
