version: "3"
services:
    mininet:
        image: maciresearch/mininet_worker
        build: ./mininet_worker
        tty: true
        privileged: true
        environment:
            - DISPLAY
        volumes:
            - /lib/modules:/lib/modules
        depends_on: 
            - maci-backend
        restart: always
        hostname: mininet
