version: "3"
services:
    ns3:
        build: 
            context: ./ns3_worker
        tty: true
        privileged: true
        volumes:
            - /lib/modules:/lib/modules
            - worker-files:/worker
        depends_on:
            - maci-backend
        restart: always
        hostname: ns3

volumes:
    simulation-framework:
    simulation-files:
    jupyter-files:
    worker-files:
