version: "3"
services:
    ns3:
        image: maciresearch/ns3_worker
        build: ./ns3_worker
        tty: true
        privileged: true
        volumes:
            - /lib/modules:/lib/modules
        depends_on:
            - maci-backend
        restart: always
        hostname: ns3
